version: "3.8"

services:
  management-api:
    image: "postgres:15"
    container_name: "management-api"
    ports:
      - "5432:5432"
    restart: "unless-stopped"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - $HOME/postgresql:/var/lib/postgresql
